// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterLocationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LocationRecords []*LocationRecord      `protobuf:"bytes,2,rep,name=locationRecords,proto3" json:"locationRecords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterLocationResponse) Reset() {
	*x = RegisterLocationResponse{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocationResponse) ProtoMessage() {}

func (x *RegisterLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocationResponse.ProtoReflect.Descriptor instead.
func (*RegisterLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterLocationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterLocationResponse) GetLocationRecords() []*LocationRecord {
	if x != nil {
		return x.LocationRecords
	}
	return nil
}

type RegisterLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocationRequest) Reset() {
	*x = RegisterLocationRequest{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocationRequest) ProtoMessage() {}

func (x *RegisterLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocationRequest.ProtoReflect.Descriptor instead.
func (*RegisterLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterLocationRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *RegisterLocationRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type LocationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRecord) Reset() {
	*x = LocationRecord{}
	mi := &file_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRecord) ProtoMessage() {}

func (x *LocationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRecord.ProtoReflect.Descriptor instead.
func (*LocationRecord) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{2}
}

func (x *LocationRecord) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *LocationRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{3}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\blocation\"v\n" +
	"\x18RegisterLocationResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12B\n" +
	"\x0flocationRecords\x18\x02 \x03(\v2\x18.location.LocationRecordR\x0flocationRecords\"\x85\x01\n" +
	"\x17RegisterLocationRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x14.location.CoordinateR\n" +
	"coordinate\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"d\n" +
	"\x0eLocationRecord\x124\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x14.location.CoordinateR\n" +
	"coordinate\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude2l\n" +
	"\x0fLocationService\x12Y\n" +
	"\x10RegisterLocation\x12!.location.RegisterLocationRequest\x1a\".location.RegisterLocationResponseB Z\x1eshared/proto/location;locationb\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_location_proto_goTypes = []any{
	(*RegisterLocationResponse)(nil), // 0: location.RegisterLocationResponse
	(*RegisterLocationRequest)(nil),  // 1: location.RegisterLocationRequest
	(*LocationRecord)(nil),           // 2: location.LocationRecord
	(*Coordinate)(nil),               // 3: location.Coordinate
}
var file_location_proto_depIdxs = []int32{
	2, // 0: location.RegisterLocationResponse.locationRecords:type_name -> location.LocationRecord
	3, // 1: location.RegisterLocationRequest.coordinate:type_name -> location.Coordinate
	3, // 2: location.LocationRecord.coordinate:type_name -> location.Coordinate
	1, // 3: location.LocationService.RegisterLocation:input_type -> location.RegisterLocationRequest
	0, // 4: location.LocationService.RegisterLocation:output_type -> location.RegisterLocationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
