apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-history-service
  template:
    metadata:
      labels:
        app: location-history-service
    spec:
      containers:
        - name: location-history-service
          image: ride-sharing/location-history-service
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: location-history-service
spec:
  selector:
    app: location-history-service
  ports:
    - port: 9092
      name: grpc
      targetPort: 9092
  type: ClusterIP
